# This is a basic workflow to help you get started with Actions

name: Comment Trigger Workflow

# Controls when the workflow will run
on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  say-hello:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '//deploy')
    
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello world! This workflow was triggered by a comment on a pull request."
          echo $github
